### ISSUE TITLE
[Idea] Separated Row & Column widgets

### ISSUE THREAD

**Issue by jesusrp98** [jamesblasco/layout#11]
I'd like to know if it would be interesting to implement the idea of separated `Row` & `Column` widgets, using `Gutter`.
This will allow developers to create `Column` widgets, where the children are separated according the specific `space` value.

This is how it wold be used:
```
 GuttedColumn(
  space: BreakpointValue(xs: 0.0, sm: 10.0).resolve(context),
  children: <Widget>[
    // ...
  ],
),
```

This is just an idea I had, and I'd like to know if this worth including within this package.

**Comment by jamesblasco** [comment]
Hey! Thanks for submitting this issue.

It looks interesting enough to be considered. But I don't think it would provide enough value to create two new Widgets that people would need to learn, and with the same properties that `Column` and `Row`. 

These two widgets are the most used by lots of developers and I think we can find a solution that doesn't make them to replace them.

For example, in my projects, I usually use this extension to add a Gutter in between.
```dart
extension ListUtils<T> on List<T> {
  List<T> addInBetween(T item) =>
      length <= 1 ? this : sublist(1).fold(<T>[first], (r, element) => [...r, item, element],);
}
```
That would look like this
```dart
Column(
    children: <Widget>[
        Item1(),
        Item2(),
        Item3(),
    ].addInBetween(Gutter()),
);
```
Another interesting solution would be to add a static method inside Gutter to help doing this. Similar on how [ListTile.divideTiles](https://github.com/flutter/flutter/blob/9b2d32b605630f28625709ebd9d78ab3016b2bf6/packages/flutter/lib/src/material/list_tile.dart#L884) works.

Something like:
```dart
Column(
    children: Gutter.addInBetween([
        Item1(),
        Item2(),
        Item3(),
    ], space: 20),
);
```

Let me know what you think about this

**Comment by jesusrp98** [comment]
I see your point about not reimplementing the `Column` and `Row` widgets using `Gutter` between the child.

I think the second option would work and it would be very beneficial for everybody.
One suggestion I'd make regarding your sample implementation would be to make the list argument inside the `Gutter.addInBetween` named. This way, you could check the spacing between each element, at the top of the function, not at the final, which would be optimal for large lists.

An example here: 
```
Column(
    children: Gutter.addInBetween(
        list: [
          Item1(),
          Item2(),
          Item3(),
        ],
        space: 20,
    ),
);
```

What do you think about this @jamesblasco ?

**Comment by jamesblasco** [comment]
Sounds great to me! Maybe calling it `children` instead of `list`?

**Comment by jesusrp98** [comment]
> Sounds great to me! Maybe calling it `children` instead of `list`?

Sure! I will open a PR soon related to the implementation & testing of this feature!

**Comment by deandreamatias** [comment]
With PR #12 can close this issue?
