### ISSUE TITLE
How to have Grid tiles of different length

### ISSUE THREAD

**Issue by phillausofia** [jamesblasco/layout#17]
on version: 0.6.2

I've used the fluid_layout library on a project to build a grid where the tiles had different widths. If there a way to achieve the same thing with the new library?  I saw that the fluid_layout was build using StaggeredGridView, tried to used this kind of grid delegate, but some of the children don't appear on the screen when resizing the screen.

**Comment by barbalex** [comment]
Maybe use [flutter_layout_grid](https://pub.dev/packages/flutter_layout_grid) for that?

**Comment by phillausofia** [comment]
Eventually, by looking through the code in the old library I've managed to understand how to build the same layout with this new one. To bad the documentation doesn't include more examples of how to build certain designs.

**Comment by jamesblasco** [comment]
I am sorry but I have had some busy months. 

I have been working on a layout grid package almost ready to be published that will solve most of the problems we had with the staggered_grid_view. Hope I can publish it in August/September. I will share it here once this happens
