### ISSUE TITLE
Upgrade to Flutter 3.0

### ISSUE THREAD

**Issue by benjaminschreck** [jamesblasco/layout#23]
I get the following error message since the upgrade to Flutter 3.0.

_/opt/homebrew/Caskroom/flutter/2.10.2/flutter/.pub-cache/hosted/pub.dartlang.org/layout-1.0.2/lib/src/layout.dart:134:54: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/opt/homebrew/Caskroom/flutter/2.10.2/flutter/packages/flutter/lib/src/widgets/binding.dart').
package:flutter/…/widgets/binding.dart:1
            MediaQueryData.fromWindow(WidgetsBinding.instance!.window,);_

**Comment by joanofdart** [comment]
@jamesblasco you should close this one since it was merged on #24
