### ISSUE TITLE
'Gap' version 2.x.x problem for newer version of flutter of dart.

### ISSUE THREAD

**Issue by khamalfa** [jamesblasco/layout#30]
## Environment

** Latest Layout Version:**  

## Description

****

**Apparently, Gap 2.x.x didn't work on newest version of flutter and dart**

## Steps to reproduce

1. Change gap version to ^3.0.1, by accepting PR of #28 
2. For those who really need to use this dependencies, you can use this dependencies locally:
- fork this repo 'layout' to your project
- change gap version to ^3.0.1 in <layout-directory>/pubspec.yaml
- on your project change layout to a path ;
`
layout:
    path: <layout-directory>/layout #ex: 'lib/package/layout'
`

**Comment by jamesblasco** [comment]
Thanks! I merged the PR and published a new version of the package 1.0.5 that fixes this

**Comment by khamalfa** [comment]
Thanks James, much apreciated, thankyou for making the great dependencies 🙌
