### ISSUE TITLE
Improve CHANGELOG order

### ISSUE THREAD

**Issue by deandreamatias** [jamesblasco/layout#8]
A good practice in changelog, place last version in first place

 **Expected order:**

```md
## [0.5.1] - Add nullable Layout
You can access layout safely with
Layout.maybeOf(context)

## [0.5.0] - First Version
```

**Current order:**

```md
## [0.5.0] - First Version

## [0.5.1] - Add nullable Layout
You can access layout safely with
Layout.maybeOf(context)
```

**Comment by jamesblasco** [comment]
True! Thank you for taking your time to submit the issue. 

I have fixed it. It will be available in pub.dev in the next release
